version: "3.8"

services:
  postgres:
    image: postgres:16.8
    platform: linux/amd64
    ports:
      - "5431:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - .:/app

  app:
    build:
      context: ./client/
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_module:/app/node_module

volumes:
  local_pgdata:
  pgadmin-data:
  node_module: {}
